// <auto-generated />
namespace HiQo.StaffManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_Connectings_in_DataBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Connectings_in_DataBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171249344_Change_Connectings_in_DataBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
